import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./_components/Navigation/Navigation";
import { Providers } from "./providers";
import Footer from "./_components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " flex flex-col bg-gray-100"}>
        <Providers>
          <Navigation />
          <main className="mx-auto w-full max-w-6xl flex-1 px-2">
            <div className="min-h-screen">{children}</div>
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
