import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./_components/Navigation/Navigation";
import { ContextProviders } from "./ContextProviders";
import Footer from "./_components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " flex flex-col bg-gray-100"}>
        <ContextProviders>
          <Navigation />
          <main className="mx-auto w-full max-w-6xl flex-1 px-2 *:min-h-[70vh]">
            {children}
          </main>
          <Footer />
        </ContextProviders>
        <script
          src="https://api-maps.yandex.ru/2.1/?apikey=7b588521-5efc-4725-937e-a21787051879&lang=en_US"
          async
          defer
        ></script>
      </body>
    </html>
  );
}
